// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPXFFUyXFf9BWvqZxWtpty9VqBupIOQxE',
    appId: '1:784297689551:web:c112536823a6a766e892ba',
    messagingSenderId: '784297689551',
    projectId: 'scale3c-test-99123',
    authDomain: 'scale3c-test-99123.firebaseapp.com',
    storageBucket: 'scale3c-test-99123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA0fJrMB7r8CZ1R-HqK6SWhdoiCYNStSg',
    appId: '1:784297689551:android:82cd243a98072664e892ba',
    messagingSenderId: '784297689551',
    projectId: 'scale3c-test-99123',
    storageBucket: 'scale3c-test-99123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnNHz4slNlFzAs1RVHhzfY6TEekZTQBjM',
    appId: '1:784297689551:ios:9dadb3ade389af6fe892ba',
    messagingSenderId: '784297689551',
    projectId: 'scale3c-test-99123',
    storageBucket: 'scale3c-test-99123.appspot.com',
    iosClientId: '784297689551-cviolp2cqeno93p90de73quumpc4c5vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.testTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnNHz4slNlFzAs1RVHhzfY6TEekZTQBjM',
    appId: '1:784297689551:ios:9dadb3ade389af6fe892ba',
    messagingSenderId: '784297689551',
    projectId: 'scale3c-test-99123',
    storageBucket: 'scale3c-test-99123.appspot.com',
    iosClientId: '784297689551-cviolp2cqeno93p90de73quumpc4c5vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.testTask',
  );
}
